### ISSUE TITLE
How is this better than a dApp using only the connected MetaMask wallet address and associated password?

### ISSUE THREAD

**Issue by enewhuis** [Edoumou/blockchain-based-authentication#1]
This seems to add extra steps to what is already secured by the wallet and requires the user to remember three more pieces of information in addition to the wallet's password and recovery phrase.

**Comment by Edoumou** [comment]
the password and the 6 digit code are needed just to increase the security. Imagine the case someone have access to your public and private keys, then they could connect to the app with your credential if only signature is needed. However, if one put some more steps like username, password and digit code to the authentication process, then public and private keys will not suffice to access the app, on the other hand, username, password and digit code are not enough to authenticate, since the user must provide the right signature with their account.

So all these steps allow to have a more secure authentication process.
